### PR TITLE
feat: store expiration

### PR DESCRIPTION
**Pull request by lukashroch**
This PR allows to set state expiration per store

### CODE REVIEW

**Comment by prazdevs** [comment]
Any context for that ? I dont really see a point in this. Seems like adding a lot of infos for a very niche concept that can be implemented through hooks 🤔

**Comment by lukashroch** [comment]
Hi,

it allows to easily get rid of old stale client data based on time conditions.

For one store, I guess it's OK using hooks. But if you want to have that for many stores, you would need to implement same logic all over stores, which just clutters it. And logic for this won't be just hooks as you would at least need to "stamp" the store data. At the moment, they are not stamped in any way, so one doesn't know how old they are.

**Comment by prazdevs** [comment]
Why not defining a custom storage that handles the expiration logic? That way it can easily be reused across stores? 🤔

**Comment by lukashroch** [comment]
Yeah no problem, there are definitely few ways how to get this done, not arguing about that. Just thought it could be useful optional way to provide store expiration. Only time is probably too limited, could also accept callback for custom logic.

Same argument probably applies to other configs already in place , like `paths`, doable with hooks and custom storage, so plugin could be even leaner 🙂

**Comment by prazdevs** [comment]
Mmh, that kind of relates to #19 in some way of allowing finer config for persistence right ?

**Comment by lukashroch** [comment]
Sort of I guess, expiration could be set per store like in this PR, and also on each storage item of array proposed in the issue.

Though idea was more generic, it's all sort of cache data in the end, so I found very useful to be able to set expiration on that.

**Comment by prazdevs** [comment]
That's why I'm skeptical about implenting it in the plugin, as cache does not belong in store persistence itself, but more in what kind of storage one is using

**Comment by prazdevs** [comment]
I should maybe consider an example of time-limited storage definition in the docs

**Comment by lukashroch** [comment]
ok cache might not have been right word to use, but persistence should not really imply that it's always infinite.

**Comment by prazdevs** [comment]
> ok cache might not have been right word to use, but persistence should not really imply that it's always infinite.

Hence why I said it should be a storage problem. And that storage should be able to invalidate (like cookies), but it's out of the scope of the plugin IMO. Data expiration belongs in the storage implementation, not the tool that links Pinia stores and the storage (i.e. this plugin). Does that make sense ? :)

**Comment by lukashroch** [comment]
That's alright, didn't realize the scope of the plugin is that narrow :-)

I'll close this.

**Comment by prazdevs** [comment]
> That's alright, didn't realize the scope of the plugin is that narrow :-)
> 
> I'll close this.

The main idea was to replicate the behaviour of vuex-persistedstate, and keep things simple and offer an easy binding between pinia stores and any kind of (sync) storage. 
I will however consider expirable storage implementation examples in the docs.

**Pull request closed without merging**
