### PR TITLE
✨ Add async storage to the plugin

### PR DESCRIPTION
**Pull request by jopicornell**
### Why
In the web ecosystem, a lot of things have been done synchronously to simplify browser APIs. That's the case for WebStorage, which spec is thirteen years old, which means Promises weren't a thing, and callbacks were the standard for asynchronous operations. This is no longer the case, having promises built in the browser, asynchronous operations are much easier to handle than before. 

WebStorage has its limitations, a few of them being limited space, slow for more than 2MB of data and it can't be used in WebWorkers. But the biggest limitation for me and my usage of this plugin is that there are environments other than the web that this plugin could be very useful, for example, Ionic. In Ionic, storage (@Ionic/storage package and @capacitor/storage) is asynchronous, which makes using this plugin a hard thing. Not only Ionic is asynchronous, but IndexedDB, the recommended storage for large amounts of data is asynchronous as well.

Another thing that could be argued, is that this plugin already has some asynchronous hooks like beforeRestore and afterRestore, but one of the things I love about this plugin is its simplicity. By making a few simple changes to the code we can make everything compatible with synchronous code, and asynchronous as well. All tests were left untouched and passing, which means this code should not impact current usage.

### Limitations
The unique limitation I see using this solution is that we check if getItem and setItem are a Promise with instanceof. That's not a problem if you use built-in Promises, but if you use any other library this won't work. I don't see it as a problem, because it is highly recommended to use built-in Promises and I don't see why anyone would do otherwise.

### Ionic Example
```

import { Storage } from '@ionic/storage';

type StorageType = {
  storage: Storage;
  initialized: boolean;
  getItem(key: string): Promise<string | null>;
  setItem(key: string, value: string): Promise<void>;
}

export const IonicStorage: StorageType = {
  storage: new Storage(),
  initialized: false,
  async getItem(key: string): Promise<string | null> {
    if (!this.initialized) {
      await this.storage.create()
    }
    return await this.storage.get(key);
  },

  async setItem(key: string, value: string): Promise<void> {
    if (!this.initialized) {
      await this.storage.create()
    }
    await this.storage.set(key, value);
  }
}


export const useAuthStore = () => {
  const ecosystemService = useEcosystemService();
  return defineStore<'auth', AuthState, AuthGetters, AuthActions>({
    id: 'auth',
    state: () => ({
      authenticated: false,
      authToken: null,
      user: null,
      loading: true,
    }),
    getters: {
      isAuthenticated(state: AuthState) {
        if (state.user === null) {
          return false;
        }
      },
      hasStoredUser: (state: AuthState) => state.user !== null,
      isLoading(state: AuthState) {
        return state.loading;
      },
    },
    actions: {
      async login(loginRequest: LoginRequest) {
        const loginResponse = await ecosystemService.post<LoginRequest>('/session', loginRequest);
        this.user = loginResponse.data as User;
        this.authenticated = true;
        return this.user;
      },
      async waitForAuthentication() {
        if (!this.isLoading) {
          return Promise.resolve()
        }
        return new Promise(resolve => {
          const unsubscribe = watch(this, (state) => {
            if (!state.loading) {
              console.log(state.loading)
              unsubscribe();
              resolve();
            }
          })
        })
      },
      logout() {
        console.log('logout');
      },
    },
    persist: {
      storage: IonicStorage,
      afterRestore(context: PiniaPluginContext) {
        context.store.loading = false;
      }
    }
  })();
};
```

As you can see, I've made a "waitForAuthentication" which is useful for me to make the code wait for the store to finish loading from the disk. Hope you see this PR useful!

### CODE REVIEW

**Comment by prazdevs** [comment]
Hi, I like the idea, I just need to make asynchronocity wont cause issues when saving, like some Promise race that could cause stale data to be persisted ? or something like this. I'll look into it.

Also, you pushed a yarn lockfile, when the package uses [pnpm](https://pnpm.io)

**Comment by jopicornell** [comment]
> Hi, I like the idea, I just need to make asynchronocity wont cause issues when saving, like some Promise race that could cause stale data to be persisted ? or something like this. I'll look into it.
> 
> Also, you pushed a yarn lockfile, when the package uses [pnpm](https://pnpm.io)

Hi, Thank you for taking this into account. I'll do some tests as I'm already using it in a product for my contractor. Also, I'll try to gove it a thought and read the code to make sure it's safe. I'll let you know if I find something

I'm sorry about the yarn.lock, idk why I introduced it, I'll remove it from my PR.

**Comment by jopicornell** [comment]
Hi @prazdevs !

I've been working on considering race conditions. IMO code is a bit ugly, but as you can see, previous tests weren't modified. Testing this has been a bit of a nightmare because we are combining synchronous code with asynchronous side effects, but now it works as expected. I've made those new tests using TDD, and I rolled back the last changes between tests to make sure I've fixed the problems.

If anyone has any suggestions or improvements, feel free to say so.

**Comment by prazdevs** [comment]
We can get somewhere with it working, but as i'm thinking of V2 rn, and it is planned to allow multiple configs. So it'll also need to consider that kind of race (tho it's advanced usage, and will be warned anyways). 

I'll see if we can make the code smh cleaner?

**Comment by jopicornell** [comment]
Please, feel free to clean and discuss anything with me, I'll be pleased to help you. I'll try to think about improvements that we can make as well. If you think about anything, I can try to implement it if you can't spend time in this. As I understand from your message, will this be part of V2 then?

**Comment by prazdevs** [comment]
was in a process to change company, but i got some free time now. I'll try to work on making a new branch with how V2 and advanced configs will be, and you can then add the async things and we'll make it clean :) ill link the branch once i'm done with scaffolding the thing

**Comment by prazdevs** [comment]
alright, i merged the (big) refactor into the main branch to get ready for V2, i let you do however you feel to re-implement it / move it into what the plugin is now. Code is still very very common with what v1 was. lmk if you have any issues. I'm still working on the contributing docs as well

**Comment by prazdevs** [comment]
I'll close it for now, for the sake of keeping the repo clean, feel free to reopen or create a new one to implement it :)

**Comment by tomheno** [comment]
Hi ! 
I also need to use an async Storage (as I am using Capacitor Preferences, which uses async Set/GetItem).
If I understood well @prazdevs, if I want to create a MR for it, I should apply the changes @jopicornell made on the current main branch, that was updated in between to be ready for V2 ?

Thanks in advance !

**Comment by jopicornell** [comment]
> Hi ! I also need to use an async Storage (as I am using Capacitor Preferences, which uses async Set/GetItem). If I understood well @prazdevs, if I want to create a MR for it, I should apply the changes @jopicornell made on the current main branch, that was updated in between to be ready for V2 ?
> 
> Thanks in advance !

Hi @tomheno, 

Thank you too! If you want to create a MR, I'll be happy to review it and test it as well. If you don't have time, let me know and  I'll try to find some time for this.

**Comment by prazdevs** [comment]
> Hi ! I also need to use an async Storage (as I am using Capacitor Preferences, which uses async Set/GetItem). If I understood well @prazdevs, if I want to create a MR for it, I should apply the changes @jopicornell made on the current main branch, that was updated in between to be ready for V2 ?
> 
> Thanks in advance !

yeah kind of, would have to go into some deep checks and regression testing to avoid breaking any working feature.
im still thinking/rewriting the way we handle storages to allow an easier time using all kinds of storage, but ngl, the sync character of pinia makes it a challenge

**Comment by rendomnet** [comment]
A lot people need this feature

**Comment by rendomnet** [comment]
@jopicornell can we use/test your solution somehow?

**Pull request closed without merging**
